### PR TITLE
Added missing BeneficiaryRequirements properties and global security

### PR DESCRIPTION
**Pull request by nkobber**

### CODE REVIEW

**Comment by eXeDK** [comment]
@EAddario maybe I could have you take a look at this while you are at it?

Thanks a lot
Team Lunar Way

**Comment by EAddario** [comment]
Beat me to the punch :-)

Will do.

**Comment by eXeDK** [comment]
Haha sorry about that ;-)

Sounds great though.

**Comment by nkobber** [comment]
@EAddario I created #70 instead.

**Pull request closed without merging**
